// python-fullstack/frontend/src/components/TodoList.tsx
import { useState, useEffect } from 'react';
import { api, Todo } from '../api/client';
import './TodoList.css';

export default function TodoList() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [newTodo, setNewTodo] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isConnected, setIsConnected] = useState(false);

  useEffect(() => {
    checkConnection();
    loadTodos();
  }, []);

  const checkConnection = async () => {
    try {
      await api.checkHealth();
      setIsConnected(true);
    } catch (err) {
      setIsConnected(false);
      setError('Failed to connect to backend');
    }
  };

  const loadTodos = async () => {
    try {
      setLoading(true);
      const data = await api.getTodos();
      setTodos(data);
      setError(null);
      setIsConnected(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load todos');
      setIsConnected(false);
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTodo.trim()) return;

    try {
      const todo = await api.createTodo({ title: newTodo.trim() });
      setTodos([...todos, todo]);
      setNewTodo('');
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create todo');
    }
  };

  const handleToggle = async (todo: Todo) => {
    try {
      const updated = await api.updateTodo(todo.id, {
        completed: !todo.completed,
      });
      setTodos(todos.map((t) => (t.id === todo.id ? updated : t)));
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update todo');
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await api.deleteTodo(id);
      setTodos(todos.filter((t) => t.id !== id));
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete todo');
    }
  };

  if (loading) {
    return <div className="loading">Loading todos...</div>;
  }

  return (
    <div className="todo-list">
      <div className="connection-status">
        <span className={`status-indicator ${isConnected ? 'connected' : 'disconnected'}`}>
          {isConnected ? '● Connected' : '● Disconnected'}
        </span>
      </div>

      {error && (
        <div className="error-message">
          {error}
          <button onClick={loadTodos} className="retry-button">
            Retry
          </button>
        </div>
      )}

      <form onSubmit={handleCreate} className="todo-form">
        <input
          type="text"
          value={newTodo}
          onChange={(e) => setNewTodo(e.target.value)}
          placeholder="What needs to be done?"
          className="todo-input"
          disabled={!isConnected}
        />
        <button type="submit" className="add-button" disabled={!isConnected}>
          Add Todo
        </button>
      </form>

      <div className="todos">
        {todos.length === 0 ? (
          <p className="empty-state">No todos yet. Add one above!</p>
        ) : (
          todos.map((todo) => (
            <div key={todo.id} className={`todo-item ${todo.completed ? 'completed' : ''}`}>
              <div className="todo-content">
                <input
                  type="checkbox"
                  checked={todo.completed}
                  onChange={() => handleToggle(todo)}
                  className="todo-checkbox"
                />
                <span className="todo-title">{todo.title}</span>
              </div>
              <button onClick={() => handleDelete(todo.id)} className="delete-button">
                Delete
              </button>
            </div>
          ))
        )}
      </div>

      <div className="todo-stats">
        <span>
          {todos.filter((t) => !t.completed).length} of {todos.length} remaining
        </span>
      </div>
    </div>
  );
}

// go-fullstack/frontend/src/components/TodoList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import TodoItem from './TodoItem.vue'
import { apiClient } from '../api/client'
import type { Todo } from '../types'

const todos = ref<Todo[]>([])
const newTodoTitle = ref('')
const isLoading = ref(false)
const error = ref<string | null>(null)

const loadTodos = async () => {
  isLoading.value = true
  error.value = null

  try {
    todos.value = await apiClient.getTodos()
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load todos'
    console.error('Error loading todos:', err)
  } finally {
    isLoading.value = false
  }
}

const createTodo = async () => {
  const title = newTodoTitle.value.trim()
  if (!title) return

  error.value = null

  try {
    const newTodo = await apiClient.createTodo({ title })
    todos.value.unshift(newTodo)
    newTodoTitle.value = ''
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to create todo'
    console.error('Error creating todo:', err)
  }
}

const handleUpdate = async (id: number, updates: { title?: string; completed?: boolean }) => {
  error.value = null

  try {
    const updatedTodo = await apiClient.updateTodo(id, updates)
    const index = todos.value.findIndex(t => t.id === id)
    if (index !== -1) {
      todos.value[index] = updatedTodo
    }
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to update todo'
    console.error('Error updating todo:', err)
    // Reload todos to revert UI changes
    await loadTodos()
  }
}

const handleDelete = async (id: number) => {
  error.value = null

  try {
    await apiClient.deleteTodo(id)
    todos.value = todos.value.filter(t => t.id !== id)
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to delete todo'
    console.error('Error deleting todo:', err)
    // Reload todos in case of error
    await loadTodos()
  }
}

const handleSubmit = (e: Event) => {
  e.preventDefault()
  createTodo()
}

onMounted(() => {
  loadTodos()
})
</script>

<template>
  <div class="todo-list-container">
    <div class="error-banner" v-if="error">
      {{ error }}
      <button @click="error = null" class="close-button">×</button>
    </div>

    <form @submit="handleSubmit" class="todo-form">
      <input
        v-model="newTodoTitle"
        type="text"
        placeholder="What needs to be done?"
        class="todo-input"
        :disabled="isLoading"
      />
      <button type="submit" :disabled="!newTodoTitle.trim() || isLoading" class="add-button">
        Add
      </button>
    </form>

    <div class="todo-stats">
      <span>{{ todos.length }} {{ todos.length === 1 ? 'item' : 'items' }}</span>
      <span v-if="todos.length > 0">
        {{ todos.filter(t => t.completed).length }} completed
      </span>
    </div>

    <div v-if="isLoading && todos.length === 0" class="loading">
      Loading todos...
    </div>

    <div v-else-if="todos.length === 0" class="empty-state">
      <p>No todos yet. Add one above to get started!</p>
    </div>

    <ul v-else class="todo-list">
      <TodoItem
        v-for="todo in todos"
        :key="todo.id"
        :todo="todo"
        @update="handleUpdate"
        @delete="handleDelete"
      />
    </ul>
  </div>
</template>

<style scoped>
.todo-list-container {
  width: 100%;
}

.error-banner {
  background-color: rgba(239, 68, 68, 0.1);
  border: 1px solid rgba(239, 68, 68, 0.3);
  color: #ef4444;
  padding: 1rem;
  border-radius: 8px;
  margin-bottom: 1rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.close-button {
  background: none;
  border: none;
  font-size: 1.5rem;
  color: #ef4444;
  cursor: pointer;
  padding: 0;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.close-button:hover {
  color: #dc2626;
}

.todo-form {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.todo-input {
  flex: 1;
}

.add-button {
  background-color: #646cff;
  color: white;
  border: none;
}

.add-button:hover:not(:disabled) {
  background-color: #535bf2;
}

.add-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.todo-stats {
  display: flex;
  justify-content: space-between;
  font-size: 0.9rem;
  color: rgba(255, 255, 255, 0.6);
  margin-bottom: 1rem;
  padding: 0 0.5rem;
}

.loading,
.empty-state {
  text-align: center;
  padding: 3rem 1rem;
  color: rgba(255, 255, 255, 0.5);
}

.todo-list {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

@media (prefers-color-scheme: light) {
  .todo-stats {
    color: rgba(0, 0, 0, 0.6);
  }

  .loading,
  .empty-state {
    color: rgba(0, 0, 0, 0.5);
  }
}
</style>
